### ISSUE TITLE
Propuesta de Funciones

### ISSUE THREAD

**Issue by Manuss20** [RITSI/demo-recuento-votos#1]
Tal y como esta mostrada la plataforma, podriamos intentar implementar una cosilla, conoceis lo mandos estos con botones, pues algo parecido intentar implementar con el , que yo dispongo de uno, y que funcione con los drives suyo.

Y otra cosa es que estos datos pueden ser almacenados para estudiarlos en Asambleas posteriores. 

Grandes @imobilis @Ryckes

**Comment by Ryckes** [comment]
En las JEEM utilizamos unos manditos que ellos llamaban clickers. Venian numerados y tenian un teclado numerico del 0 al 9 además de \* y #. Tengo entendido que fueron muy, muy, muy caros. Los usaban para todas las votaciones, se integraban con las presentaciones y se mostraba el resultado tras cerrar la elección. El problema es que tenían que ir diciendole a la gente que votara, que no se olvidara, y para eso hay que saber en todo momento qué socios hay presentes, si todos los representantes han abandonado la sala, etc. Si no, no sabes si falta gente por votar o no.
